use new action to upload SDK version info

diff --git a/.github/workflows/release-workflow.yml b/.github/workflows/release-workflow.yml
--- a/.github/workflows/release-workflow.yml
+++ b/.github/workflows/release-workflow.yml
@@ -24,6 +24,28 @@ jobs:
     runs-on: ubuntu-latest
     timeout-minutes: 60
     steps:
+      - name: Ensure required variables and secrets are set
+        run: |
+          if [ -z "${{ vars.SDK_VERSION_URL }}" ]; then
+            echo "Missing required variable: SDK_VERSION_URL"
+            exit 1
+          fi
+          
+          if [ -z "${{ secrets.SDK_VERSION_TOKEN }}" ]; then
+            echo "Missing required secret: SDK_VERSION_TOKEN"
+            exit 1
+          fi
+
+      - name: Validate access to version data service
+        uses: embrace-io/public-actions/upload-sdk-version@v1
+        with:
+          platform: 'android'
+          version: ${{ inputs.rc_version }}
+          dryRun: true
+          sdkVersionUrl: ${{ vars.SDK_VERSION_URL }}
+        env:
+          SDK_VERSION_TOKEN: ${{ secrets.SDK_VERSION_TOKEN }}
+
       - name: Checkout SDK
         uses: actions/checkout@v4
         with:
@@ -42,6 +64,16 @@ jobs:
       - name: Release to Maven Central
         run: |
           ./gradlew findSonatypeStagingRepository releaseSonatypeStagingRepository -Dorg.gradle.parallel=false --no-build-cache --no-configuration-cache --stacktrace
+
+      - name: Record SDK Version History
+        uses: embrace-io/public-actions/upload-sdk-version@v1
+        with:
+          platform: 'android'
+          version: ${{ inputs.rc_version }}
+          dryRun: false
+          sdkVersionUrl: ${{ vars.SDK_VERSION_URL }}
+        env:
+          SDK_VERSION_TOKEN: ${{ secrets.SDK_VERSION_TOKEN }}
 
   publish-api-docs:
     name: Publish API Docs to GitHub Pages
